Price decrease
audrius-savickas/se-wasted-app pull request #172
Opened 2021-11-04 10:12 UTC by DonatasPuc

Implemented price decrease. I don't know if it is the optimal solution, but currently the client can pick price decrease type (either "AMOUNT" or "PERCENT") by which current price is calculated and returned in a FoodResponse dto.

2021-11-04 10:49 UTC, audrius-savickas commented on backend/Persistence/DB/Data/Test/Foods.json
> +    "DecreaseType": "PERCENT",
I think we should use enums for `DecreaseType`, for example 0 for percent type, and 1 for value type

2021-11-04 10:49 UTC, audrius-savickas commented on backend/Persistence/DB/Data/Test/Foods.json
> +    "DecreaseType": "PERCENT",
foods.json should have foods with decrease type of value as well, not only percent like right now

2021-11-04 10:49 UTC, audrius-savickas commented on backend/Persistence/DB/Data/Test/Foods.json
> +    "DecreaseType": "string",
string?

2021-11-04 10:50 UTC, audrius-savickas commented on backend/Domain/Entities/Food.cs
> +        private const string PERCENT_STR = "PERCENT";
move these to enum

2021-11-04 10:55 UTC, audrius-savickas requested changes
I'm not sure if this exception throwing in `Food.cs` constructor is the most effective, I think you can improve the readability a bit

2021-11-04 12:35 UTC, DonatasPuc commented
Changed DecreaseType to enum. Added validation to api's for validating DecreaseType enum value. Improved data in joods.json.

Refactored Food constructor, but I still don't know if it's ok.

Also, where should I document what enum values mean in the web api?

2021-11-05 08:36 UTC, DominykasSip approved these changes

2021-11-05 09:25 UTC, JesusGonzalezA approved these changes

2021-11-05 09:29 UTC, JesusGonzalezA commented
> Also, where should I document what enum values mean in the web API?

We should, but we would have to import new packages or create new classes just to alter the documentation UI. I believe it takes time and it does not really give us a huge increase of value. For me it is correct leaving it alone for now

2021-11-05 09:31 UTC, merged